### ISSUE TITLE
JavaScript Capstone Project - Setup

### ISSUE THREAD

**Issue by adamilare** [adamilare/javascript-capstone#22]
(Kanban board link) https://github.com/adamilare/javascript-capstone/projects/1

There are two members in this team.

**Comment by m05e5** [comment]
Hi @adamilare , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the link to your kanban board please kindly add it and resubmit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Stephen-Adom** [comment]
@m05e5 Thank you for pointing out our mistake🙏
